name = "labstrap"
license = "MIT"
licenselink = "https://github.com/xguse/hugo_labstrap/blob/master/LICENSE.md"
description = "labstrap is Twitter Bootstrap based theme.Inspired by Beg."
homepage = "https://github.com/xguse/hugo_labstrap"
tags = ["blog", "bootstrap"]
features = ["blog"]

[author]
    name = "Gus Dunn"
    homepage = "https://github.com/xguse"

